### ISSUE TITLE
Delete my repository

### ISSUE THREAD

**Issue by uvvxyz** [education/Series-Intro-to-GitHub-Flow#5]
To whoever it concerns,

I have finished my intro to github flow lessons and i want to delete this repo, but i am unable to.
Will someone plz do anything about it?
will be waiting to hear from you, guys

**Comment by IzumiKoshiro** [comment]
Same here.

**Comment by vacaramin** [comment]
@uvvxyz delete the forked/created-from-template repo 
to delete that, go to settings -> delete repository

**Comment by uvvxyz** [comment]
That's the issue,bro.There is no option such as Settings to delete the repo
![Screenshot 2024-01-12 112532](https://github.com/education/Series-Intro-to-GitHub-Flow/assets/145991224/03c2e7e9-979d-4c2e-b4dd-29138c432abd)

**Comment by vacaramin** [comment]
@uvvxyz  you're in the wrong repository, go to your forked copy of this repository and delete it from there. 
If you are asking if you can delete this repository because you have finished the lessons from this repo. You can't cuz you don't own this repository, neither does deleting this repo makes sense. it's a public repo
